---
name: Test_addon
version: dev
slug: example
description: Example add-on by Community Home Assistant Add-ons
url: https://github.com/mikevansighem/test_addon
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
