---
name: Test_addon
version: "0.3.1"
slug: test_addon
description: "Upload your Hass.io backups to Dropbox"
url: https://github.com/mikevansighem/test_addon
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
stdin: true
hassio_api: true
hassio_role: manager
boot: auto
map: [backup, share]

# Fields available in configuration tab with default values.
options:
  log_level: info
  seconds_between_quotes: 5
  oauth_access_token: "<YOUR_ACCESS_TOKEN>"
  output: ""

# Types
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
  oauth_access_token: str
  output": str
  keep_last": int(0,)?
  filetypes": str?

# Download location of the package.
image: "ghcr.io/mikevansighem/test_addon/{arch}"
