---
name: Test_addon
version: "0.4.0"
slug: test_addon
description: "Upload your Home Assistant backups to Dropbox"
url: https://github.com/mikevansighem/test_addon
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
stdin: true
hassio_api: true
hassio_role: manager
boot: auto
map: [backup, share]

# Fields available in configuration tab with default values.
options:
  oauth_app_key: "<YOUR_APP_KEY>"
  oauth_app_secret: "<YOUR_APP_SECRET>"
  output: "/backup/"

# Types
schema:
  oauth_access_token: str
  oauth_app_key: str
  oauth_app_secret: str
  output: str
  keep_last: int(0,)?
  filetypes: str?

# Download location of the package.
image: "ghcr.io/mikevansighem/test_addon/{arch}"
