---
name: Test_addon
version: dev
slug: test_addon
description: My first test addon.
url: https://github.com/mikevansighem/test_addon
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: "ghcr.io/mikevansighem/test_addon/{arch}"
